In [1]:
#Import basic packages
import os
import numpy as np
import pandas as pd
import csv
import regex as re
import datetime as dt

In [2]:
#import outcome file with org_uuid
main_df = pd.read_csv(R"d:/msc-project/data/final/outcome_final.csv",encoding='utf-8',
                         index_col='org_uuid',
                         parse_dates= ['founded_on','seed_date','series_a_date','series_b_date','series_c_date'])
main_processing_df = main_df[['name','outcome']]

In [4]:
main_df.head(3)

,name,status,founded_on,seed_date,series_a_date,series_b_date,series_c_date,num_funding_rounds,duration_to_acquisition_years,duration_to_ipo_years,duration_to_closed_years,duration_to_current_years,duration_to_seed_years,duration_to_series_a_years,duration_to_series_b_years,duration_to_series_c_years,outcome
org_uuid,,,,,,,,,,,,,,,,,
000014da-0c46-b9cb-0941-3a93c027b119,Resilio,operating,2016-11-01,NaT,NaT,NaT,NaT,7.0,NaN,NaN,NaN,4.2,NaN,NaN,NaN,NaN,0
00002470-bff7-6226-5800-0ca1b3787b6f,Codementor,operating,2013-01-01,2013-08-05,NaT,NaT,NaT,5.0,NaN,NaN,NaN,8.0,0.59,NaN,NaN,NaN,0
000095de-8e2b-82f1-32a7-c222ba3d5682,Ultraprise Loan Technologies,operating,2001-01-01,NaT,NaT,NaT,NaT,1.0,NaN,NaN,NaN,20.0,NaN,NaN,NaN,NaN,0

In [5]:
#import main organisation csv
org_ori_df = pd.read_csv(R"d:/msc-project/data/pre-processed/organisations_preprocessed.csv",encoding='utf-8',
                         index_col='org_uuid',
                         parse_dates= ['founded_on','went_public_on','acquired_on','closed_on'])

In [6]:
org_ori_df.head(3)

,name,legal_name,homepage_url,country_code,state_code,region,city,address,postal_code,status,...,acquirer_state_code,acquirer_region,acquirer_city,acquisition_type,acquired_on,price_usd,price,price_currency_code,parent_uuid,parent_name
org_uuid,,,,,,,,,,,,,,,,,,,,,
e1393508-30ea-8a36-3f96-dd3226033abd,Wetpaint,NaN,http://www.wetpaint.com/,USA,NY,New York,New York,902 Broadway 11th Floor New,10010,acquired,...,NY,New York,New York,acquisition,2013-12-16,30000000.0,30000000.0,USD,NaN,NaN
5f2b40b8-d1b3-d323-d81a-b7a8e89553d0,Digg,"Digg Holdings, LLC",http://www.digg.com,USA,NY,New York,New York,NaN,NaN,acquired,...,NY,New York,New York,acquisition,2012-07-12,16000000.0,16000000.0,USD,NaN,NaN
df662812-7f97-0b43-9d3e-12f64f504fbb,Facebook,"Facebook, Inc.",http://www.facebook.com,USA,CA,California,Menlo Park,1 Hacker Way,94025,ipo,...,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN

In [7]:
org_ori_df.columns

Index(['name', 'legal_name', 'homepage_url', 'country_code', 'state_code',
       'region', 'city', 'address', 'postal_code', 'status',
       'short_description', 'category_list', 'category_groups_list',
       'num_funding_rounds', 'total_funding_usd', 'total_funding',
       'total_funding_currency_code', 'founded_on', 'last_funding_on',
       'closed_on', 'employee_count', 'email', 'phone', 'facebook_url',
       'linkedin_url', 'twitter_url', 'logo_url', 'primary_role', 'num_exits',
       'description', 'ipo_uuid', 'stock_exchange_symbol', 'stock_symbol',
       'went_public_on', 'share_price_usd', 'share_price',
       'share_price_currency_code', 'valuation_price_usd', 'valuation_price',
       'valuation_price_currency_code', 'money_raised_usd', 'money_raised',
       'money_raised_currency_code', 'acquisition_uuid', 'acquirer_uuid',
       'acquirer_name', 'acquirer_country_code', 'acquirer_state_code',
       'acquirer_region', 'acquirer_city', 'acquisition_type', 'acquired_on',
       'price_usd', 'price', 'price_currency_code', 'parent_uuid',
       'parent_name'],
      dtype='object')

In [47]:
org_processing = org_ori_df[['category_list','category_groups_list']]

In [13]:
org_processing.head(3)

,category_list,category_groups_list
org_uuid,,
e1393508-30ea-8a36-3f96-dd3226033abd,"Publishing,Social Media,Social Media Management","Content and Publishing,Internet Services,Media..."
5f2b40b8-d1b3-d323-d81a-b7a8e89553d0,"Internet,Social Media,Social Network","Internet Services,Media and Entertainment"
df662812-7f97-0b43-9d3e-12f64f504fbb,"Mobile Apps,Social,Social Media,Social Network...","Apps,Community and Lifestyle,Content and Publi..."

In [27]:
#create a list of unique categories
categories_list = list(org_processing['category_list'])
unique_categories = set()

for category_list in categories_list:
    category_list = category_list.split(',')
    for category in category_list:
        unique_categories.add(category)
        
unique_categories = list (unique_categories)
unique_categories.sort()

In [49]:
#assign one hot encode for category_list for each company

for category in unique_categories:
    column_name = 'is_'+category.lower().replace(' ','_')
    one_hot = list()

    for category_list in categories_list:
        category_list = category_list.split(',')
        if category in category_list:
            one_hot.append(1)
        else:
            one_hot.append(0)

    org_processing[column_name]=one_hot

C:\Users\Abdul Rahim Ab Ghani\miniconda3\lib\site-packages\ipykernel_launcher.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [50]:
org_processing.head(3)

,category_list,category_groups_list,is_3d_printing,is_3d_technology,is_a/b_testing,is_accounting,is_ad_exchange,is_ad_network,is_ad_retargeting,is_ad_server,...,is_wired_telecommunications,is_wireless,is_women's,is_wood_processing,is_xbox,is_young_adults,is_esports,is_ios,is_mhealth,is_macos
org_uuid,,,,,,,,,,,,,,,,,,,,,
e1393508-30ea-8a36-3f96-dd3226033abd,"Publishing,Social Media,Social Media Management","Content and Publishing,Internet Services,Media...",0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5f2b40b8-d1b3-d323-d81a-b7a8e89553d0,"Internet,Social Media,Social Network","Internet Services,Media and Entertainment",0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
df662812-7f97-0b43-9d3e-12f64f504fbb,"Mobile Apps,Social,Social Media,Social Network...","Apps,Community and Lifestyle,Content and Publi...",0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [51]:
#create a list of unique category groups
groups_list = list(org_processing['category_groups_list'])
unique_groups = set()

for group_list in groups_list:
    group_list = group_list.split(',')
    for group in group_list:
        unique_groups.add(group)
        
unique_groups = list (unique_groups)
unique_groups.sort()

In [54]:
len(unique_groups)

47

In [ ]:
#assign one hot encode for category_list for each company

for group in unique_groups:
    column_name = 'is_'+group.lower().replace(' ','_')
    one_hot = list()

    for group_list in groups_list:
        group_list = group_list.split(',')
        if group in group_list:
            one_hot.append(1)
        else:
            one_hot.append(0)

    org_processing[column_name]=one_hot