In [25]:
import pandas as pd
from ast import literal_eval

In [3]:
data = pd.read_csv("combined_ner_output_org.csv", index_col=0)
data

,article_id,union,intersection,intersection_al2
0,0,['FamPay'],['FamPay'],['FamPay']
1,1,"['ApplyBoard', 'Education Testing Services', '...","['ApplyProof', 'GRE', 'ApplyBoard', 'ETS']","['Ontario Teachers Pension Plan', 'ApplyBoard'..."
2,2,"['Nubank', 'EC-1', 'TC Mobility', 'Extra Crunch']",['Nubank'],['Nubank']
3,3,"['iZettle', 'Creandum']",[],['iZettle']
4,4,['Heliogen'],['Heliogen'],['Heliogen']
...,...,...,...,...
4889,4889,"['Arista Networks', 'CarGurus', 'EA', 'Despega...","['TripAdvisor', 'HP']","['Arista Networks', 'HP', 'TripAdvisor', 'Micr..."
4890,4890,"['Intel', 'Moovit', 'Equity']",['Intel'],['Intel']
4891,4891,"['Namogoo', 'Personali']","['Namogoo', 'Personali']","['Namogoo', 'Personali']"
4892,4892,"['NASA', 'Founders Factory', 'Marriott Hotel',...",[],"['NASA', 'PPE', 'Founders Factory', 'TrueSight..."
4893,4893,"['Otonomo', 'SK Holdings', 'Partners', 'GDPR',...",[],['Otonomo']

In [36]:
# average entities per article tagged using union
u_len = []
for i in range(len(data)):
    u_len.append(len(literal_eval(data.iloc[i]['union'])))
print("Average entities per article: ", sum(u_len)/len(data))

Average entities per article:  7.903759705762158

In [43]:
# average entities per article tagged using intersection + number of empty intersections
i_len = []
if_zero = 0
for i in range(len(data)):
    i_len.append(len(literal_eval(data.iloc[i]['intersection'])))
    if len(literal_eval(data.iloc[i]['intersection'])) == 0:
        if_zero += 1
print("Number of empty intersections: ", if_zero)
print("Average entities per article: ", sum(i_len)/len(data))
print("Percentage of empty intersections: ", if_zero/len(data))

Number of empty intersections:  3043
Average entities per article:  0.5674295055169596
Percentage of empty intersections:  0.6217817736003269

In [44]:
# average entities per article tagged using intersection_al2 + number of empty intersection_al2
al_len = []
if_zero = 0
for i in range(len(data)):
    al_len.append(len(literal_eval(data.iloc[i]['intersection_al2'])))
    if len(literal_eval(data.iloc[i]['intersection_al2']))==0:
        if_zero += 1
print("Number of empty intersections: ", if_zero)
print("Average entities per article: ", sum(al_len)/len(data))
print("Percentage of empty intersections: ", if_zero/len(data))

Number of empty intersections:  394
Average entities per article:  2.223539027380466
Percentage of empty intersections:  0.0805067429505517

In [46]:
article_data =  pd.read_csv("techcrunch_articles.csv", index_col=0)
article_data

,title,author,date,body
0,"FamPay, a fintech aimed at teens in India, rai...",Manish Singh,2021/06/15,\nHow big is the market in India for a neobank...
1,Edtech investors are flocking to SaaS guidance...,Natasha Mascarenhas,2021/06/15,"\n\nApplyBoard, a startup that helps internati..."
2,"Extra Crunch roundup: TC Mobility recaps, Nuba...",Annie Siebert,2021/06/15,"\nWhat, exactly, are investors looking for?\nE..."
3,How to identify unicorn founders when they’re ...,Johan Brenner,2021/06/15,\n\n\n\n\nJohan Brenner\nContributor\n\n\n\n\n...
4,Solar concentration startup Heliogen basks in ...,Devin Coldewey,2021/06/15,"\nSunlight is a great source of energy, but it..."
...,...,...,...,...
4889,Tech stocks open lower ahead of another busy e...,Alex Wilhelm,2020/05/04,\nThe optimism that confounded many in April m...
4890,"Equity Monday: Intel covets Moovit, two early ...",Alex Wilhelm,2020/05/04,\n\nGood morning and welcome back to TechCrunc...
4891,Customer journey hijacking prevention tool Nam...,Steve O'Hear,2020/05/04,"\nNamogoo, the Israel-based company that has d..."
4892,Oxwash bags $1.7M for a cleaner spin on laundry,Natasha Lomas,2020/05/04,"\nOxwash, a UK-based laundry startup that’s ai..."
4893,Otonomo raises $46 million to expand its autom...,Kirsten Korosec,2020/05/01,\nNew vehicles today can produce a treasure tr...

In [49]:
data2 = data
data2['article_body'] = article_data['body']
data2 = data2.sample(n=100)

In [52]:
data2.to_csv("random_article_samples_annotated.csv", encoding='utf-8-sig', sep='~')

In [53]:
data2['true_positives'] = None

In [56]:
data2
data2['true_positives'].iloc[0] = ['Outschool', 'ClassDojo', 'Quizlet', 'Applyboard', 'Pitchbook', 'GSV Ventures', 'Firework Ventures', 'Cowboy Ventures', '' ]

e:\university\dissertation\code\dissertations-2021-info\kasturi_mitra_find\lib\site-packages\pandas\core\indexing.py:1637: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_block(indexer, value, name)

In [57]:
data2

,article_id,union,intersection,intersection_al2,article_body,true_positives
1911,1911,"['TopHat', 'GetSetUp', 'Quizlet', 'Nearpod', '...","['ClassDojo', 'TLCom Capital', 'DreamBox', 'Yo...","['Union Square Ventures', 'YouSchool', 'Guild ...",\nThe venture potential of a startup that cate...,[Trump]
4250,4250,"['Sophie Alcorn', 'Trump', 'TechCrunch', 'Harv...",[],"['TechCrunch', 'Trump']",\nThe Trump administration’s decision to exten...,None
1390,1390,"['Fazz Financial Group', 'Xfers', 'Payfazz']",['Xfers'],"['Fazz Financial Group', 'Xfers']","\nPayfazz and Xfers, two startups that want to...",None
1328,1328,"['Tackle', 'Microsoft', 'Google', 'Bessemer Ve...",[],"['ARR', 'API', 'APIs', 'AWS', 'PagerDuty']",\nEach of the big three cloud vendors — Amazon...,None
2134,2134,"['Healthvana', 'Apple', 'LA County', 'Google']",[],['Healthvana'],\nAs the vaccination campaign to counter COVID...,None
...,...,...,...,...,...,...
2055,2055,['OKR'],['OKR'],['OKR'],"\nLast year, a number of startups building OKR...",None
2864,2864,"['Apple', 'Kandji', 'MDM', 'Capital Group', 'C...",[],['Apple'],"\nKandji, a mobile device management (MDM) sta...",None
1918,1918,"['Teltech', 'IAC', 'Confide']",['IAC'],"['IAC', 'Confide', 'Teltech']","\nIAC has acquired Confide, the encrypted mobi...",None
4615,4615,"['D-ID', 'TechCrunch Startup Battlefield', 'Cl...",[],['D-ID'],\nIf only Facebook had been using the kind of ...,None
2115,2115,"['The/Studio', 'TAM', 'Harvard', 'Black', 'For...","['TAM', 'SuppliedShop', 'UC Berkeley', 'Harvard']","['Harvard', 'TAM', 'SuppliedShop', 'Stanford',...",\n\n\n\n\nJoseph Heller\nContributor\n\n\n\n\t...,None

In [82]:
# count words in articles
word_count = []
for i in range(0, len(data)):
    word_count.append(len(data['article_body'].iloc[i].split()))
print("Sum: ", sum(word_count), "Average: ", sum(word_count)/len(word_count))

Sum:  3029627 Average:  619.0492439722109

In [83]:
data['article_body'].iloc[0]

'\nHow big is the market in India for a neobank aimed at teenagers? Scores of high-profile investors are backing a startup to find out.\nBangalore-based FamPay said on Wednesday it has raised $38 million in its Series A round led by Elevation Capital. General Catalyst, Rocketship VC, Greenoaks Capital and existing investors Sequoia Capital India, Y Combinator, Global Founders Capital and Venture Highway also participated in the new round, which brings FamPay’s to-date raise to $42.7 million.\nThe size of the new investment makes it one of the largest Series A rounds in India. TechCrunch reported early this month that FamPay was in talks with Elevation Capital to raise a new round.\nFounded by Sambhav Jain and Kush Taneja (pictured above) — both of whom graduated from Indian Institute of Technology, Roorkee in 2019 — FamPay enables teenagers to make online and offline payments.\nThe thesis behind the startup, said Jain in an interview with TechCrunch, is to provide financial literacy to teenagers, who additionally have limited options to open a bank account in India at a young age. Through gamification, the startup said it’s making lessons about money fun for youngsters.\nUnlike in the U.S., where it’s common for teenagers to get jobs at restaurants and other places and understand how to handle money at a young age, a similar tradition doesn’t exist in India.\nAfter gathering the consent from parents, FamPay provides teenagers with an app to make online purchases, as well as plastic cards — the only numberless card of its kind in the country — for offline transactions. Parents credit money to their children’s FamPay accounts and get to keep track of high-ticket spendings.\nIn other markets, including the U.S., a number of startups including Greenlight, Step and Till Financial are chasing to serve the teenagers, but in India, there currently is no startup looking to solve the financial access problem for teenagers, said Mridul Arora, a partner at Elevation Capital, in an interview with TechCrunch.\nIt could prove to be a good issue to solve — India has the largest adolescent population in the world.\n“If you’re able to serve them at a young age, over a course of time, you stand to become their go-to product for a lot of things,” Arora said. “FamPay is serving a population that is very attractive and at the same time underserved.”\nThe current offerings of FamPay are just the beginning, said Jain. Eventually the startup wishes to provide a range of services and serve as a neobank for youngsters to retain them with the platform forever, he said, though he didn’t wish to share currently what those services might be.\nImage Credits: FamPay\nTeens represent the “most tech-savvy generation, as they haven’t seen a world without the internet,” he said. “They adapt to technology faster than any other target audience and their first exposure with the internet comes from the likes of Instagram and Netflix. This leads to higher expectations from the products that they prefer to use. We are unique in approaching banking from a whole new lens with our recipe of community and gamification to match the Gen Z vibe.”\n“I don’t look at FamPay just as a payments service. If the team is able to execute this, FamPay can become a very powerful gateway product to teenagers in India and their financial life. It can become a neobank, and it also has the opportunity to do something around social, community and commerce,” said Arora.\nDuring their college life, Jain and Taneja collaborated and built an app and worked at a number of startups, including social network ShareChat, logistics firm Rivigo and video streaming service Hotstar. Jain said their work with startups in the early days paved the idea to explore a future in this ecosystem.\nPrior to arriving at FamPay, Jain said the duo had thought about several more ideas for a startup. The early days of FamPay were uniquely challenging to the founders, who had to convince their parents about their decision to do a startup rather than joining firms or startups as had most of their peers from college. Until being selected by Y Combinator, Jain said he didn’t even fully understand a cap table and dilutions.\nHe credited entrepreneurs such as\xa0Kunal Shah (founder of CRED) and Amrish Rau (CEO of Pine Labs) for being generous with their time and guidance. They also wrote some of the earliest checks to the startup.\nThe startup, which has amassed over 2 million registered users, plans to deploy the fresh capital to expand its user base and product offerings, and hire engineers. It is also looking for people to join its leadership team, said Jain.\n\n'