## Get all the data repository

In [5]:
import os

In [6]:
for i,j,k in os.walk("data/"):
    print(i,j,k)

data/ [] ['acquisitions.csv', 'category_groups.csv', 'checksum.csv', 'degrees.csv', 'doc_frequencies.tsv', 'events.csv', 'event_appearances.csv', 'frequencies.tsv', 'funding_rounds.csv', 'funds.csv', 'GoogleNews-vectors-negative300.bin', 'investments.csv', 'investment_partners.csv', 'investors.csv', 'ipos.csv', 'jobs.csv', 'organizations.csv', 'organization_descriptions.csv', 'org_parents.csv', 'people.csv', 'people_descriptions.csv']

## Read the original data

In [7]:
import pandas as pd
category_groups = pd.read_csv("data/category_groups.csv")
people_descriptions = pd.read_csv("data/people_descriptions.csv")
people = pd.read_csv("data/people.csv")
organization_descriptions = pd.read_csv("data/organization_descriptions.csv")
org_parents = pd.read_csv("data/org_parents.csv")
organizations = pd.read_csv("data/organizations.csv")
degrees = pd.read_csv("data/degrees.csv")

## Deal with people data

In [8]:
people_descriptions = people_descriptions[["uuid","name","description"]]

In [9]:
people = people[["uuid","name","gender","featured_job_organization_uuid","featured_job_organization_name","featured_job_title"]]

In [10]:
people_all = pd.merge(people, people_descriptions, how='left', on=['uuid', 'name'])

In [11]:
people_all.columns = ['p_uuid', 'p_name', 'gender', 'uuid',
       'name', 'featured_job_title', 'p_description']

In [12]:
people_all

,p_uuid,p_name,gender,uuid,name,featured_job_title,p_description
0,ed13cd36-fe2b-3707-197b-0c2d56e37a71,Ben Elowitz,male,cf253887-5eac-21a2-28d3-47db7311f7e9,Madrona Venture Group,Managing Director,Ben Elowitz is co-founder and CEO of [Wetpaint...
1,5ceca97b-493c-1446-6249-5aaa33464763,Kevin Flaherty,male,789e5e4d-0c90-d06e-92a0-b800b461c3da,DRSmedia,Team Member,"Brand development, creative agency management,..."
2,9f99a98a-aa97-b30b-0d36-db67c1d277e0,Raju Vegesna,male,bf4d7b0e-b34d-2fd8-d292-6049c4f7efc7,Zoho,Chief Evangelist,Raju is an evangelist for Zoho and is one of t...
3,6e1bca72-a865-b518-b305-31214ce2d1b0,Ian Wenig,male,bf4d7b0e-b34d-2fd8-d292-6049c4f7efc7,Zoho,VP Business Development,Ian Wenig has more then twenty years experienc...
4,3b598c59-7b6c-2d48-763c-da55bca77035,Owen Byrne,male,NaN,NaN,NaN,Legend has it that Owen Byrne was hired by [Di...
...,...,...,...,...,...,...,...
1099616,3cd24783-8319-4b1c-9faa-bf5f221061da,Jens Kempf,male,NaN,NaN,NaN,Wir legen viel Wert auf eine individuelle und ...
1099617,b1b9554d-9961-449b-b94c-ff0f94545b1b,Anthony Ivanovsky,male,NaN,NaN,NaN,"Customer success, IT management, and marketing..."
1099618,052edfa2-2be6-4c5d-9cc0-a3c9010c76eb,J. Gerard Aguilar,male,NaN,NaN,NaN,A recognized expert in the areas of VoIP and d...
1099619,9e0b20e8-55ab-4c72-9f3f-2dc78b71edaf,Sadiyah Khan,female,NaN,NaN,NaN,NaN
1099620,6d00ddc9-f96e-4a0e-af24-bc65797e2d61,Sayid Khan,male,NaN,NaN,NaN,NaN

## deal with organization data

In [13]:
organizations_select = organizations[["uuid","name","rank","roles","status","short_description","category_list","category_groups_list","num_funding_rounds","employee_count","founded_on"]]

In [14]:
organization_descriptions = organization_descriptions[["uuid","name","description"]]

In [15]:
organizatio_all = pd.merge(organizations_select, organization_descriptions, how='left', on=['uuid', 'name'])

In [16]:
organizatio_all.head()

,uuid,name,rank,roles,status,short_description,category_list,category_groups_list,num_funding_rounds,employee_count,founded_on,description
0,e1393508-30ea-8a36-3f96-dd3226033abd,Wetpaint,131437.0,company,acquired,Wetpaint offers an online social publishing pl...,"Publishing,Social Media,Social Media Management","Content and Publishing,Internet Services,Media...",3.0,51-100,2005-06-01,Wetpaint is a technology platform company that...
1,bf4d7b0e-b34d-2fd8-d292-6049c4f7efc7,Zoho,7682.0,"investor,company",operating,"Zoho offers a suite of business, collaboration...","Cloud Computing,Collaboration,CRM,Developer To...","Administrative Services,Information Technology...",NaN,1001-5000,1996-09-15,"Zoho offers a suite of business, collaboration..."
2,5f2b40b8-d1b3-d323-d81a-b7a8e89553d0,Digg,13152.0,company,acquired,Digg Inc. operates a website that enables its ...,"Internet,Social Media,Social Network","Internet Services,Media and Entertainment",6.0,51-100,2004-10-11,Digg Inc. operates a website that enables its ...
3,f4d5ab44-058b-298b-ea81-380e6e9a8eec,Omidyar Network,1757.0,investor,operating,Omidyar Network is an investment firm.,"Enterprise Software,Financial Services,Venture...","Financial Services,Lending and Investments,Sof...",NaN,101-250,2004-01-01,"Pierre Omidyar, the founder of eBay, and his w..."
4,df662812-7f97-0b43-9d3e-12f64f504fbb,Facebook,5.0,"investor,company",ipo,Facebook is an online social networking servic...,"Mobile Apps,Social,Social Media,Social Network...","Apps,Community and Lifestyle,Content and Publi...",17.0,10000+,2004-02-04,Facebook is an online social networking servic...

## deal with degree data

In [17]:
degrees = degrees[["uuid","name","person_uuid","person_name","institution_uuid","institution_name","degree_type","subject"]]

In [18]:
degrees.columns = ["d_uuid","d_name","p_uuid","p_name","ins_uuid","ins_name","degree_type","subject"]

In [19]:
people_all_plus_degree = pd.merge(people_all, degrees, how='left', on=['p_uuid', 'p_name'])

In [20]:
people_all_plus_degree.head(5)

,p_uuid,p_name,gender,uuid,name,featured_job_title,p_description,d_uuid,d_name,ins_uuid,ins_name,degree_type,subject
0,ed13cd36-fe2b-3707-197b-0c2d56e37a71,Ben Elowitz,male,cf253887-5eac-21a2-28d3-47db7311f7e9,Madrona Venture Group,Managing Director,Ben Elowitz is co-founder and CEO of [Wetpaint...,2b2b344b-e74a-5c9a-b308-341f79c6fe9f,BS Electrical Engineering/Computer Science @ ...,10f9a25b-9675-2281-486e-a52955c706df,"University of California, Berkeley",BS,Electrical Engineering/Computer Science
1,ed13cd36-fe2b-3707-197b-0c2d56e37a71,Ben Elowitz,male,cf253887-5eac-21a2-28d3-47db7311f7e9,Madrona Venture Group,Managing Director,Ben Elowitz is co-founder and CEO of [Wetpaint...,be3b1fce-5a88-0cc7-ffe3-0908d273e69a,BS Applied Mathematics @ University of Califo...,10f9a25b-9675-2281-486e-a52955c706df,"University of California, Berkeley",BS,Applied Mathematics
2,5ceca97b-493c-1446-6249-5aaa33464763,Kevin Flaherty,male,789e5e4d-0c90-d06e-92a0-b800b461c3da,DRSmedia,Team Member,"Brand development, creative agency management,...",97e39d22-d4ab-7283-5e85-d1d51116d396,BBA unknown @ Washington University in St. Louis,6ae9957a-8fb4-0ab1-73fa-dd547c4d3da4,Washington University in St. Louis,BBA,unknown
3,5ceca97b-493c-1446-6249-5aaa33464763,Kevin Flaherty,male,789e5e4d-0c90-d06e-92a0-b800b461c3da,DRSmedia,Team Member,"Brand development, creative agency management,...",7aaaa052-0b81-81aa-3ff8-17f59fcb707e,MBA unknown @ Indiana University,3b4faff0-708e-8c1c-83f0-6fea01016519,Indiana University,MBA,unknown
4,9f99a98a-aa97-b30b-0d36-db67c1d277e0,Raju Vegesna,male,bf4d7b0e-b34d-2fd8-d292-6049c4f7efc7,Zoho,Chief Evangelist,Raju is an evangelist for Zoho and is one of t...,NaN,NaN,NaN,NaN,NaN,NaN

In [21]:
final_data = pd.merge(organizatio_all, people_all_plus_degree, how='left', on=['uuid', 'name'])

In [22]:
final_data.columns

Index(['uuid', 'name', 'rank', 'roles', 'status', 'short_description',
       'category_list', 'category_groups_list', 'num_funding_rounds',
       'employee_count', 'founded_on', 'description', 'p_uuid', 'p_name',
       'gender', 'featured_job_title', 'p_description', 'd_uuid', 'd_name',
       'ins_uuid', 'ins_name', 'degree_type', 'subject'],
      dtype='object')

In [44]:
final_data

,uuid,name,rank,roles,status,short_description,category_list,category_groups_list,num_funding_rounds,employee_count,...,p_name,gender,featured_job_title,p_description,d_uuid,d_name,ins_uuid,ins_name,degree_type,subject
0,e1393508-30ea-8a36-3f96-dd3226033abd,Wetpaint,131437.0,company,acquired,Wetpaint offers an online social publishing pl...,"Publishing,Social Media,Social Media Management","Content and Publishing,Internet Services,Media...",3.0,51-100,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,bf4d7b0e-b34d-2fd8-d292-6049c4f7efc7,Zoho,7682.0,"investor,company",operating,"Zoho offers a suite of business, collaboration...","Cloud Computing,Collaboration,CRM,Developer To...","Administrative Services,Information Technology...",NaN,1001-5000,...,Raju Vegesna,male,Chief Evangelist,Raju is an evangelist for Zoho and is one of t...,NaN,NaN,NaN,NaN,NaN,NaN
35,5f2b40b8-d1b3-d323-d81a-b7a8e89553d0,Digg,13152.0,company,acquired,Digg Inc. operates a website that enables its ...,"Internet,Social Media,Social Network","Internet Services,Media and Entertainment",6.0,51-100,...,Joshua Auerbach,male,Board Member,Venture Partner at Betaworks Studio. Formerl...,967b2ae6-5842-ca27-59b9-acd60b7b4c42,BA Economics @ Harvard University,d8b57c0e-9f0f-4dcb-d207-a12a90c64a2d,Harvard University,BA,Economics
38,f4d5ab44-058b-298b-ea81-380e6e9a8eec,Omidyar Network,1757.0,investor,operating,Omidyar Network is an investment firm.,"Enterprise Software,Financial Services,Venture...","Financial Services,Lending and Investments,Sof...",NaN,101-250,...,Salvatore Giambanco,male,Partner of Human Capital & Operations Functions,Sal leads the human capital and operations fun...,49ae5af2-25fe-b1d1-e19e-11f45a04a4c4,B.A. Economics & Political Science @ Columbia...,8d297d1e-3e3d-fadd-2963-57e0a40bff2a,Columbia University,B.A.,Economics & Political Science
148,df662812-7f97-0b43-9d3e-12f64f504fbb,Facebook,5.0,"investor,company",ipo,Facebook is an online social networking servic...,"Mobile Apps,Social,Social Media,Social Network...","Apps,Community and Lifestyle,Content and Publi...",17.0,10000+,...,Mark Zuckerberg,male,Founder & CEO,Mark Zuckerberg is the founder and CEO of Face...,e75e1434-2ace-9255-2da8-3943f5bbae7c,Dropped Out Computer Science @ Harvard Univer...,d8b57c0e-9f0f-4dcb-d207-a12a90c64a2d,Harvard University,Dropped Out,Computer Science
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1718514,09c8e895-e62e-46f0-93f9-45e088ede007,AngelNV,NaN,investor,operating,Early stage investor school and investment fun...,NaN,NaN,NaN,unknown,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1718515,9b7c50d5-8d96-4af4-9b0e-af72705184e9,Science Delivered,NaN,company,operating,Science Delivered promote quality science educ...,Education,Education,NaN,1-10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1718516,98589112-e90c-434b-a4e7-ffaa12eee602,OmniPanel,NaN,company,operating,OmniPanel is an analytics platform that surfac...,NaN,NaN,1.0,unknown,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1718517,90418618-ce0c-49b2-8c0b-1f741a3d313e,Schafer Logistics Inc,NaN,company,operating,Schafer Logistics Inc provides integrate exper...,Transportation,Transportation,NaN,51-100,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1718518,8418f326-1ac2-4cb0-8ddf-2bee51e23546,True Footage,NaN,company,operating,A real estate data authentication platform tha...,NaN,NaN,1.0,unknown,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [24]:
final_data = final_data.drop_duplicates(["uuid","name"])

In [25]:
final_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1216445 entries, 0 to 1718518
Data columns (total 23 columns):
 #   Column                Non-Null Count    Dtype
---  ------                --------------    -----
 0   uuid                  1216445 non-null  object
 1   name                  1216431 non-null  object
 2   rank                  1216311 non-null  float64
 3   roles                 1207572 non-null  object
 4   status                1216445 non-null  object
 5   short_description     1216327 non-null  object
 6   category_list         1138386 non-null  object
 7   category_groups_list  1138386 non-null  object
 8   num_funding_rounds    191956 non-null   float64
 9   employee_count        1216445 non-null  object
 10  founded_on            956138 non-null   object
 11  description           661704 non-null   object
 12  p_uuid                251235 non-null   object
 13  p_name                251235 non-null   object
 14  gender                250632 non-null   object
 15  featured_job_title    251226 non-null   object
 16  p_description         147135 non-null   object
 17  d_uuid                79500 non-null    object
 18  d_name                74140 non-null    object
 19  ins_uuid              79500 non-null    object
 20  ins_name              79500 non-null    object
 21  degree_type           77406 non-null    object
 22  subject               74737 non-null    object
dtypes: float64(2), object(21)
memory usage: 222.7+ MB

In [82]:
final_data = final_data.reset_index(drop=True)

In [83]:
final_data.to_pickle("final.pkl")

In [112]:
test_data = final_data.dropna(subset = ["description"])

In [139]:
test_data = test_data.reset_index(drop=True)
test_data.to_pickle("test.pkl")

## baseline version

In [142]:
test_data = pd.read_pickle("test.pkl")

In [151]:
baseline_data = test_data[["uuid","name","status","founded_on","description","short_description","p_description","category_list"]]

- Get the ranked founded time
- Companies without founded time fill with time now

In [152]:
from datetime import datetime
def parse_ymd(s):
    year_s, mon_s, day_s = s.split('-')
    return datetime(int(year_s), int(mon_s), int(day_s))

In [153]:
baseline_data["founded_on"] = baseline_data["founded_on"].fillna(str(datetime.now()).split()[0])

<ipython-input-153-72c71dd1850c>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  baseline_data["founded_on"] = baseline_data["founded_on"].fillna(str(datetime.now()).split()[0])

In [154]:
baseline_data["founded_on"] = baseline_data["founded_on"].apply(lambda x:parse_ymd(x))

<ipython-input-154-afebc508d809>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  baseline_data["founded_on"] = baseline_data["founded_on"].apply(lambda x:parse_ymd(x))

- One hot encoding for investment status

In [155]:
status_one_hot = pd.get_dummies(baseline_data["status"])

In [156]:
baseline_data = pd.concat([baseline_data,status_one_hot],axis=1)

In [157]:
baseline_data.to_pickle("baseline.pkl")

In [150]:
baseline_data

,uuid,name,status,founded_on,description,short_description,p_description,acquired,closed,ipo,operating
0,e1393508-30ea-8a36-3f96-dd3226033abd,Wetpaint,acquired,2005-06-01 00:00:00,Wetpaint is a technology platform company that...,Wetpaint offers an online social publishing pl...,NaN,1,0,0,0
1,bf4d7b0e-b34d-2fd8-d292-6049c4f7efc7,Zoho,operating,1996-09-15 00:00:00,"Zoho offers a suite of business, collaboration...","Zoho offers a suite of business, collaboration...",Raju is an evangelist for Zoho and is one of t...,0,0,0,1
2,5f2b40b8-d1b3-d323-d81a-b7a8e89553d0,Digg,acquired,2004-10-11 00:00:00,Digg Inc. operates a website that enables its ...,Digg Inc. operates a website that enables its ...,Venture Partner at Betaworks Studio. Formerl...,1,0,0,0
3,f4d5ab44-058b-298b-ea81-380e6e9a8eec,Omidyar Network,operating,2004-01-01 00:00:00,"Pierre Omidyar, the founder of eBay, and his w...",Omidyar Network is an investment firm.,Sal leads the human capital and operations fun...,0,0,0,1
4,df662812-7f97-0b43-9d3e-12f64f504fbb,Facebook,ipo,2004-02-04 00:00:00,Facebook is an online social networking servic...,Facebook is an online social networking servic...,Mark Zuckerberg is the founder and CEO of Face...,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...
661699,a64d3f29-f00d-4a60-9a61-b2f710bbfc19,Talk Howdy,operating,2020-03-01 00:00:00,Talk Howdy is an online community platform. Th...,Build and discover online communities through ...,NaN,0,0,0,1
661700,e14386d9-2f49-4fd6-a8a7-e54b7f2c3380,Botin,operating,2020-12-14 00:00:00,Digital Broker App of U.S Securities for Latin...,Turning Latin Americans into shareholders of t...,NaN,0,0,0,1
661701,bb47222d-e371-4f5b-9741-f7988ec969c8,TidBit,operating,2021-07-18 00:00:00,Tidbits are creatively and beautiful free info...,"Tidbit is a intuitive, web-based, infographic ...",NaN,0,0,0,1
661702,78fc105f-432b-45ef-ab0e-c5a620778775,Nereus Advisors,operating,2014-01-01 00:00:00,Nereus Advisors is founded and led by Bruce Co...,Advisory & Consulting,NaN,0,0,0,1
661703,fd1ea9cb-46a5-467e-acec-c01a6538a823,Angelico Ventures,operating,2008-01-01 00:00:00,Angelico Ventures is a life science focused ve...,Impactful Investment Banking for Entrepreneurs...,NaN,0,0,0,1

## Connecting the database

In [162]:
! pip install pymongo[srv]

Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Requirement already satisfied: pymongo[srv] in c:\users\70473\anaconda3\lib\site-packages (3.12.0)
Collecting dnspython<2.0.0,>=1.16.0
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/ec/d3/3aa0e7213ef72b8585747aa0e271a9523e713813b9a20177ebe1e939deb0/dnspython-1.16.0-py2.py3-none-any.whl (188 kB)
Installing collected packages: dnspython
  Attempting uninstall: dnspython
    Found existing installation: dnspython 2.1.0
    Uninstalling dnspython-2.1.0:
      Successfully uninstalled dnspython-2.1.0
Successfully installed dnspython-1.16.0

In [164]:
import pymongo
client = pymongo.MongoClient("mongodb+srv://xing:1234@cluster0.nzkme.mongodb.net/myFirstDatabase?retryWrites=true&w=majority")
db = client.test

ConfigurationError: The "dnspython" module must be installed to use mongodb+srv:// URIs. To fix this error install pymongo with the srv extra:
 C:\Users\70473\Anaconda3\python.exe -m pip install "pymongo[srv]"